name: otp_timer
description: Help you to create timer base features like otp. work with id so it change handle multiple timers.
version: 0.0.5
homepage: https://b1101-portfolio.web.app
repository: https://github.com/P-B1101/otp-timer

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: